In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
titanic = pd.read_csv('/content/titanic_dataset.csv')

In [3]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic.set_index('PassengerId', inplace=True)

In [5]:
titanic

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [7]:
titanic.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
titanic.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
titanic.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

# Filling Missing Values

In [ ]:
titanic.drop(columns=['Cabin'],inplace = True)

In [ ]:
titanic['Age'].fillna(titanic['Age'].median(),inplace= True)

/tmp/ipykernel_1007/1196647189.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['Age'].fillna(titanic['Age'].median(),inplace= True)

In [ ]:
mode_embarked = titanic['Embarked'].mode()[0]
titanic['Embarked'].fillna(mode_embarked,inplace = True)

In [ ]:
titanic.isnull().sum()

In [ ]:
sns.boxplot(titanic)
plt.show()

In [ ]:
sns.boxplot(titanic['Fare'])
plt.show()

In [ ]:
q1 = titanic['Fare'].quantile(0.25)
q3 = titanic['Fare'].quantile(0.75)

iqr = q3 - q1

up_lim = q3 + (1.5 * iqr)
low_lim = q1 - (1.5 * iqr)

titanic.loc[titanic['Fare']<low_lim,'Fare']=low_lim
titanic.loc[titanic['Fare']>up_lim,'Fare']=up_lim

In [ ]:
q1 = titanic['Age'].quantile(0.25)
q3 = titanic['Age'].quantile(0.75)

iqr = q3 - q1

up_lim = q3 + (1.5 * iqr)
low_lim = q1 - (1.5 * iqr)

titanic.loc[titanic['Age']<low_lim,'Age']=low_lim
titanic.loc[titanic['Age']>up_lim,'Age']=up_lim

In [ ]:
q1 = titanic['SibSp'].quantile(0.25)
q3 = titanic['SibSp'].quantile(0.75)

iqr = q3 - q1

up_lim = q3 + (1.5 * iqr)
low_lim = q1 - (1.5 * iqr)

titanic.loc[titanic['SibSp']<low_lim,'SibSp']=low_lim
titanic.loc[titanic['SibSp']>up_lim,'SibSp']=up_lim

In [ ]:

plt.figure(figsize=(12,4))
plt.boxplot(titanic['Fare'])
plt.title('Fare after capping')

plt.show()

In [ ]:

plt.figure(figsize=(12,4))
plt.boxplot(titanic['SibSp'])
plt.title('SibSp after capping')
plt.show()

In [ ]:
plt.figure(figsize=(12,4))
plt.boxplot(titanic['Age'])
plt.title('Age after capping')

plt.show()

In [ ]:
for column in titanic.columns:
  print(column, ':' ,titanic[column].unique(),'\n')

##Encoding

In [ ]:
titanic_encoded = pd.get_dummies(titanic,dtype = 'int', columns=['Sex', 'Embarked'],drop_first = True)

In [ ]:
titanic_encoded

##Train test split

In [ ]:
# Separate features (X) and target (y)
x = titanic_encoded.drop(columns=['Survived', 'Name', 'Ticket'])
y = titanic_encoded['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size = 0.2,random_state = 42
)

In [ ]:
x_train

In [ ]:
x_test

In [ ]:
y_train

In [ ]:
y_train

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
x_train_scaled

In [ ]:
x_test_scaled

##Classification

In [ ]:
#Logistic Regression model
from sklearn.linear_model import LogisticRegression

In [ ]:
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(x_train,y_train)
y_pred_lr_model = lr_model.predict(x_test)

In [ ]:
y_pred_lr_model

In [ ]:
from sklearn.metrics import confusion_matrix,precision_score
from sklearn.metrics import accuracy_score,f1_score
from sklearn.metrics import recall_score

In [ ]:
print(confusion_matrix(y_test,y_pred_lr_model))
print('Accuracy is : ',accuracy_score(y_test,y_pred_lr_model))
print('Precision is :',precision_score(y_test,y_pred_lr_model))
print('Recall is :',recall_score(y_test,y_pred_lr_model))
print('F1 score is ',f1_score(y_test,y_pred_lr_model))

##KNN

In [ ]:
#knn
#Finding the optimum k value
from sklearn.neighbors import KNeighborsClassifier

acc_score = []
for i in range(3,10):
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(x_train,y_train)
  y_pred_knn = knn.predict(x_test)
  acc = accuracy_score(y_test,y_pred_knn)
  acc_score.append(acc)

In [ ]:
acc_score

In [ ]:
plt.plot(np.arange(3,10),acc_score,'o-')
plt.xlabel('k Value')
plt.ylabel('Accuracy score')
plt.grid()

In [ ]:
#optimum k value is 5 because accuracy is high when k = 5
#train the knn model for k = 5
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train_scaled,y_train)
y_pred_knn = knn.predict(x_test_scaled)
print(confusion_matrix(y_test,y_pred_knn))
print('Accuracy is : ',accuracy_score(y_test,y_pred_knn))
print('Precision is :',precision_score(y_test,y_pred_knn))
print('Recall is :',recall_score(y_test,y_pred_knn))
print('F1 score is ',f1_score(y_test,y_pred_knn))

##SVC

In [ ]:
#SVM
from sklearn.svm import SVC

In [ ]:
#linear Kernel
svm_linear = SVC(kernel = 'linear')
svm_linear.fit(x_train_scaled,y_train)
y_pred_svm_linear = svm_linear.predict(x_test_scaled)
print(confusion_matrix(y_test,y_pred_svm_linear))
print('Accuracy is : ',accuracy_score(y_test,y_pred_svm_linear))
print('Precision is :',precision_score(y_test,y_pred_svm_linear))
print('Recall is :',recall_score(y_test,y_pred_svm_linear))
print('F1 score is ',f1_score(y_test,y_pred_svm_linear))

In [ ]:
#polynomial Kernel
svm_poly = SVC(kernel = 'poly')
svm_poly.fit(x_train_scaled,y_train)
y_pred_svm_poly = svm_poly.predict(x_test_scaled)
print(confusion_matrix(y_test,y_pred_svm_poly))
print('Accuracy is : ',accuracy_score(y_test,y_pred_svm_poly))
print('Precision is :',precision_score(y_test,y_pred_svm_poly))
print('Recall is :',recall_score(y_test,y_pred_svm_poly))
print('F1 score is ',f1_score(y_test,y_pred_svm_poly))

In [ ]:
#rbf Kernel
svm_rbf = SVC(kernel = 'rbf')
svm_rbf.fit(x_train_scaled,y_train)
y_pred_svm_rbf = svm_rbf.predict(x_test_scaled)
print(confusion_matrix(y_test,y_pred_svm_rbf))
print('Accuracy is : ',accuracy_score(y_test,y_pred_svm_rbf))
print('Precision is :',precision_score(y_test,y_pred_svm_rbf))
print('Recall is :',recall_score(y_test,y_pred_svm_rbf))
print('F1 score is ',f1_score(y_test,y_pred_svm_rbf))

##Decision Tree

In [ ]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy',random_state = 42)
dt.fit(x_train_scaled,y_train)
y_pred_dt = dt.predict(x_test_scaled)
print(confusion_matrix(y_test,y_pred_dt))
print('Accuracy is : ',accuracy_score(y_test,y_pred_dt))
print('Precision is :',precision_score(y_test,y_pred_dt))
print('Recall is :',recall_score(y_test,y_pred_dt))
print('F1 score is ',f1_score(y_test,y_pred_dt))

##Random Forest

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(criterion = 'entropy',random_state = 42)
rf.fit(x_train_scaled,y_train)
y_pred_rf = rf.predict(x_test_scaled)
print(confusion_matrix(y_test,y_pred_rf))
print('Accuracy is : ',accuracy_score(y_test,y_pred_rf))
print('Precision is :',precision_score(y_test,y_pred_rf))
print('Recall is :',recall_score(y_test,y_pred_rf))
print('F1 score is ',f1_score(y_test,y_pred_rf))